version: '3.8'

services:
  # Backend API Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: exchange-rate-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    extra_hosts:
      # Allow backend to connect to Ollama running on host machine
      - "host.docker.internal:host-gateway"
    networks:
      - exchange-rate-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: exchange-rate-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - exchange-rate-network
    restart: unless-stopped

networks:
  exchange-rate-network:
    driver: bridge
